@echo off
echo Starting SmartCart Backend Server...
echo Checking if port 5001 is in use...
netstat -ano | findstr :5001 >nul
if %errorlevel%==0 (
    echo Port 5001 is in use. Stopping existing process...
    call stop-server.bat
    timeout /t 2 >nul
)
echo Starting server on port 5001...
npm start